version: "3"

services:
  postgres:
    image: postgres:15.4
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
    networks:
      - local-keycloak

  keycloak:
    depends_on:
      - postgres
    container_name: local_keycloak
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: "start --verbose"
    volumes:
      - ./keycloak.conf:/opt/keycloak/conf/keycloak.conf
      - ./certificate.pem:/path/to/certfile.pem
      - ./certificate-key.pem:/path/to/keyfile.pem
    networks:
      - local-keycloak

  nginx-service:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./vhost.d:/etc/nginx/vhost.d
      - ./certs:/etc/nginx/certs:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
    networks:
      - local-keycloak

networks:
  local-keycloak:
